### ISSUE TITLE
keep the '?si=' but add something else

### ISSUE THREAD

**Issue by flerpan01** [Xenorio/YTShareAntiTrack#3]
How about the idea posted here: https://www.reddit.com/r/webdev/comments/15ukrpi/comment/jzo4xug/ 

Perhaps instead of randomising a string it could point to: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016R0679 or something similar?

**Comment by xenorio** [comment]
While this would indeed be funny, it's entirely outside of the scope of this project. 

First of all, it would still provide YouTube with a means of tracking by giving them the information that the link was shared by someone who uses this script. And since only a minuscule amount of YouTube users use this script, they could potentially still identify people by connecting enough other metadata outside of URLs.

Second of all, as a side effect of removing the tracking, this script also keeps URLs short. Which is desirable to many people.

However, this is libre software, so feel free to implement this in a fork and call it "YTShareTrackingScrambler" or whatever :)
